version: '3.4'

services:
  mina-mainnet:
    container_name: mina-mainnet
    image: minaprotocol/mina-daemon:1.3.1.2-25388a0-bullseye-devnet
    restart: always
    networks:
      mina-network:
        ipv4_address: 172.28.10.10
    ports:
      - '8302:8302'
      - '3095:3095'
    expose:
      - '3095'
    command: daemon \
      --external-port 8302 \
      --rest-port 3095 \
      --insecure-rest-server \
      --file-log-level Info \
      --log-level Info \
      --peer-list-url https://storage.googleapis.com/seed-lists/devnet_seeds.txt

networks:
  mina-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/24
